import archiver from 'archiver'
import { Readable } from 'stream'
import { PLATFORM_SPECS, WALLPAPER_SPECS } from './processor'

/**
 * 创建 README 内容
 */
function createReadmeContent(generationId: string, style: string): string {
  return `
╔════════════════════════════════════════════════════════════════╗
║                  GENSHIN STYLE AVATAR PACK                     ║
║                  Generated by Anime Identity Kit                ║
╚════════════════════════════════════════════════════════════════╝

Generation ID: ${generationId}
Style: ${style}
Generated: ${new Date().toISOString()}

📦 PACKAGE CONTENTS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This package contains 18+ optimized avatar images for different platforms:

📱 SOCIAL MEDIA (01-social-media/)
  • Discord (128x128) - Perfect for Discord profiles
  • Twitter/X (400x400) - Optimized for Twitter display
  • Instagram (320x320) - Instagram profile size
  • Facebook (180x180) - Facebook profile picture
  • LinkedIn (400x400) - Professional networking
  • TikTok (200x200) - TikTok profile image

🎮 GAMING PLATFORMS (02-gaming/)
  • Steam (184x184) - Steam profile avatar
  • Xbox (1080x1080) - Xbox gamerpic
  • PlayStation (1000x1000) - PSN profile
  • Epic Games (512x512) - Epic Games profile
  • Nintendo (256x256) - Nintendo Switch profile

📺 STREAMING PLATFORMS (03-streaming/)
  • Twitch (256x256) - Twitch channel avatar
  • YouTube (800x800) - YouTube channel icon
  • Kick (300x300) - Kick streaming profile

💼 PROFESSIONAL USE (04-professional/)
  • High Resolution (1024x1024) - General high-quality use
  • Transparent Background (512x512) - For custom backgrounds
  • Print Quality (2048x2048) - Ultra-high resolution

🖼️ BONUS WALLPAPERS (05-wallpapers/)
  • Mobile Wallpaper (1080x1920) - Phone background
  • Desktop Wallpaper (1920x1080) - Computer background

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

💡 USAGE TIPS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. Use platform-specific images for best quality
2. Circular images (Discord, Twitter) already have rounded edges
3. Transparent background version is great for custom edits
4. Print quality version is suitable for merchandise/printing

🔒 LICENSE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✓ Personal use: Unlimited
✓ Social media profiles: Unlimited
✓ Gaming profiles: Unlimited
✓ Streaming channels: Unlimited
✓ Commercial use: Allowed (with credit)

✗ Redistribution: Not allowed (don't resell these images)
✗ AI training: Not allowed

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Need more avatars? Visit: https://anime-identity-kit.com

Questions? Contact: support@anime-identity-kit.com

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Enjoy your new avatar! 🎨✨
`.trim()
}

/**
 * 文件夹说明映射
 */
const FOLDER_DESCRIPTIONS: Record<string, string> = {
  'social': '01-social-media',
  'gaming': '02-gaming',
  'streaming': '03-streaming',
  'professional': '04-professional'
}

/**
 * 创建 ZIP 包
 */
export async function createAvatarZip(
  avatarBuffers: Record<string, Buffer>,
  wallpaperBuffers: Record<string, Buffer>,
  metadata: {
    generationId: string
    style: string
  }
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const archive = archiver('zip', {
      zlib: { level: 9 } // 最高压缩级别
    })

    const chunks: Buffer[] = []

    archive.on('data', (chunk: Buffer) => {
      chunks.push(chunk)
    })

    archive.on('end', () => {
      const buffer = Buffer.concat(chunks)
      console.log(`[ZipPackager] ✓ ZIP created: ${buffer.length} bytes`)
      resolve(buffer)
    })

    archive.on('error', (err) => {
      console.error('[ZipPackager] ✗ ZIP creation failed:', err)
      reject(err)
    })

    console.log('[ZipPackager] Creating ZIP package...')

    // 添加 README
    archive.append(createReadmeContent(metadata.generationId, metadata.style), {
      name: 'README.txt'
    })

    // 按平台分类添加头像
    for (const [key, buffer] of Object.entries(avatarBuffers)) {
      const spec = PLATFORM_SPECS[key]
      if (!spec) continue

      const folder = FOLDER_DESCRIPTIONS[spec.category]
      const filename = `${key}-${spec.size}.png`

      archive.append(buffer, {
        name: `${folder}/${filename}`
      })
    }

    // 添加壁纸
    for (const [key, buffer] of Object.entries(wallpaperBuffers)) {
      const spec = WALLPAPER_SPECS[key]
      if (!spec) continue

      const filename = `${key}-wallpaper-${spec.width}x${spec.height}.png`

      archive.append(buffer, {
        name: `05-wallpapers/${filename}`
      })
    }

    // 完成打包
    archive.finalize()
  })
}

/**
 * 上传 ZIP 到 Supabase Storage
 */
export async function uploadZipToSupabase(
  zipBuffer: Buffer,
  generationId: string,
  supabaseClient: any
): Promise<string> {
  const fileName = `${generationId}/avatar-pack.zip`

  console.log(`[ZipPackager] Uploading ZIP to Supabase: ${fileName}`)

  const { data, error } = await supabaseClient.storage
    .from('generated-images')
    .upload(fileName, zipBuffer, {
      contentType: 'application/zip',
      upsert: true
    })

  if (error) {
    console.error('[ZipPackager] Upload failed:', error)
    throw new Error(`Failed to upload ZIP: ${error.message}`)
  }

  // 获取公开 URL
  const { data: publicData } = supabaseClient.storage
    .from('generated-images')
    .getPublicUrl(fileName)

  console.log(`[ZipPackager] ✓ ZIP uploaded: ${publicData.publicUrl}`)

  return publicData.publicUrl
}
